
export interface Book {
  name: string;
  chapters: number;
  testament: 'old' | 'new';
}

export const booksOfBible: Book[] = [
  // Antiguo Testamento
  { name: 'Génesis', chapters: 50, testament: 'old' },
  { name: 'Éxodo', chapters: 40, testament: 'old' },
  { name: 'Levítico', chapters: 27, testament: 'old' },
  { name: 'Números', chapters: 36, testament: 'old' },
  { name: 'Deuteronomio', chapters: 34, testament: 'old' },
  { name: 'Josué', chapters: 24, testament: 'old' },
  { name: 'Jueces', chapters: 21, testament: 'old' },
  { name: 'Rut', chapters: 4, testament: 'old' },
  { name: '1 Samuel', chapters: 31, testament: 'old' },
  { name: '2 Samuel', chapters: 24, testament: 'old' },
  { name: '1 Reyes', chapters: 22, testament: 'old' },
  { name: '2 Reyes', chapters: 25, testament: 'old' },
  { name: '1 Crónicas', chapters: 29, testament: 'old' },
  { name: '2 Crónicas', chapters: 36, testament: 'old' },
  { name: 'Esdras', chapters: 10, testament: 'old' },
  { name: 'Nehemías', chapters: 13, testament: 'old' },
  { name: 'Ester', chapters: 10, testament: 'old' },
  { name: 'Job', chapters: 42, testament: 'old' },
  { name: 'Salmos', chapters: 150, testament: 'old' },
  { name: 'Proverbios', chapters: 31, testament: 'old' },
  { name: 'Eclesiastés', chapters: 12, testament: 'old' },
  { name: 'Cantares', chapters: 8, testament: 'old' },
  { name: 'Isaías', chapters: 66, testament: 'old' },
  { name: 'Jeremías', chapters: 52, testament: 'old' },
  { name: 'Lamentaciones', chapters: 5, testament: 'old' },
  { name: 'Ezequiel', chapters: 48, testament: 'old' },
  { name: 'Daniel', chapters: 12, testament: 'old' },
  { name: 'Oseas', chapters: 14, testament: 'old' },
  { name: 'Joel', chapters: 3, testament: 'old' },
  { name: 'Amós', chapters: 9, testament: 'old' },
  { name: 'Abdías', chapters: 1, testament: 'old' },
  { name: 'Jonás', chapters: 4, testament: 'old' },
  { name: 'Miqueas', chapters: 7, testament: 'old' },
  { name: 'Nahúm', chapters: 3, testament: 'old' },
  { name: 'Habacuc', chapters: 3, testament: 'old' },
  { name: 'Sofonías', chapters: 3, testament: 'old' },
  { name: 'Hageo', chapters: 2, testament: 'old' },
  { name: 'Zacarías', chapters: 14, testament: 'old' },
  { name: 'Malaquías', chapters: 4, testament: 'old' },
  
  // Nuevo Testamento
  { name: 'Mateo', chapters: 28, testament: 'new' },
  { name: 'Marcos', chapters: 16, testament: 'new' },
  { name: 'Lucas', chapters: 24, testament: 'new' },
  { name: 'Juan', chapters: 21, testament: 'new' },
  { name: 'Hechos', chapters: 28, testament: 'new' },
  { name: 'Romanos', chapters: 16, testament: 'new' },
  { name: '1 Corintios', chapters: 16, testament: 'new' },
  { name: '2 Corintios', chapters: 13, testament: 'new' },
  { name: 'Gálatas', chapters: 6, testament: 'new' },
  { name: 'Efesios', chapters: 6, testament: 'new' },
  { name: 'Filipenses', chapters: 4, testament: 'new' },
  { name: 'Colosenses', chapters: 4, testament: 'new' },
  { name: '1 Tesalonicenses', chapters: 5, testament: 'new' },
  { name: '2 Tesalonicenses', chapters: 3, testament: 'new' },
  { name: '1 Timoteo', chapters: 6, testament: 'new' },
  { name: '2 Timoteo', chapters: 4, testament: 'new' },
  { name: 'Tito', chapters: 3, testament: 'new' },
  { name: 'Filemón', chapters: 1, testament: 'new' },
  { name: 'Hebreos', chapters: 13, testament: 'new' },
  { name: 'Santiago', chapters: 5, testament: 'new' },
  { name: '1 Pedro', chapters: 5, testament: 'new' },
  { name: '2 Pedro', chapters: 3, testament: 'new' },
  { name: '1 Juan', chapters: 5, testament: 'new' },
  { name: '2 Juan', chapters: 1, testament: 'new' },
  { name: '3 Juan', chapters: 1, testament: 'new' },
  { name: 'Judas', chapters: 1, testament: 'new' },
  { name: 'Apocalipsis', chapters: 22, testament: 'new' }
];

export const popularThemes = [
  'Fe',
  'Esperanza',
  'Amor',
  'Perdón',
  'Oración',
  'Salvación',
  'Gracia',
  'Paz',
  'Gozo',
  'Acción de Gracias',
  'Sabiduría',
  'Valor',
  'Confianza en Dios',
  'Servicio',
  'Discipulado',
  'Vida Eterna',
  'Fidelidad de Dios',
  'Restauración',
  'Unidad',
  'Compasión'
];
