name: Build Lovable Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build
        run: npm run build

      - name: Exportar dist como artefato
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
